

spring:
  data:
    mongodb:
      #uri: mongodb://admin:password@localhost:27117/integrationtest-db
      #database: integrationtest-db
      uri: ${mongodb.uri}/${mongodb.database}
      database: ${mongodb.database}
server:
  port: 8180

logging:
  level:
    root: INFO
    io.github.javialc.java.labs: DEBUG


