name: Run Java Test with Maven

on:
  issue_comment:
    types: [created]

jobs:
  run-java-test:
    if: contains(github.event.comment.body, '/run-test-it')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file Java/pom.xml

    - name: Run Test with Maven
      run: mvn verify --file Java/pom.xml